version: '3.8'
services:
  pipeline: 
    build:
      context: .  # ...path to the directory containing Dockerfile (just `.`)
    ports:
      - "3838:3838" # ...force Shiny app to always run on port 3838
    volumes:
      - .:/pipeline # ...mount the current directory to the container (ensures output files are generated in the local directory)
    init: true
    environment:
      FLAGS: ""
    command: bash -c './jobscript.sh && shiny-server'